# Configuration for Gym Web Application
name = "gym-web"
compatibility_date = "2024-01-17"
pages_build_output_dir = "client/build"

[env.production]
vars = { REACT_APP_API_URL = "https://gymapp.site/api", NODE_VERSION = "18", CI = "false" }

[env.preview]
vars = { REACT_APP_API_URL = "https://preview.gymapp.site/api", NODE_VERSION = "18", CI = "false" }