# Configuration for Gym Web Application
name = "gym-web"
pages_build_output_dir = "client/build"

[build]
command = "cd client && npm install && npm run build"

[build.environment]
NODE_VERSION = "18"
CI = "false"

[vars]
REACT_APP_API_URL = "https://gymapp.site/api"

# Add KV and D1 configurations if needed later
# [[kv_namespaces]]
# binding = "KV"
# id = ""

# [[d1_databases]]
# binding = "DB"
# database_name = ""
# database_id = ""