# Configuration for Gym Web Application
name = "gym-web"

[build]
command = "cd client && npm install && CI=false npm run build"
pages_build_output_dir = "client/build"

[site]
bucket = "./client/build"

[env.production]
name = "gym-web-production"
route = { pattern = "gymapp.site/*", zone_name = "gymapp.site" }

[env.staging]
name = "gym-web-staging"
route = { pattern = "staging.gymapp.site/*", zone_name = "gymapp.site" }